### ISSUE TITLE
"Next" issues and confusing second-to-last paragraph

### ISSUE THREAD

**Issue by DanL12186** [learn-co-curriculum/using-to-json-ruby#10]
As with the previous walkthrough, this need e.preventDefault added to show.html.erb's js to work properly, or at least it did for me..

`<script type="text/javascript" charset="utf-8">`
`$(function () {`
  `$(".js-next").on("click", function(event) {`
    `event.preventDefault()`
    `var nextId = parseInt($(".js-next").attr("data-id")) + 1;`
    `$.get("/posts/" + nextId + ".json", function(data) { `
      `$(".authorName").text(data["author"]["name"]);`
      `$(".postTitle").text(data["title"]);`
      `$(".postBody").text(data["description"]);`
      `$(".js-next").attr("data-id", data["id"]);`
    `});`
  `});`
`});`
`</script>`

Also, the paragraph: 

> Instead of doing a $.get() to /posts/id/post_data, we are now
getting /posts/id.json. If we reload the page and click >out< Next
button, everything still works and we don't have to change any of the
code to extract the JSON values!

Was, at least for me, confusing. It makes it sound like the posts/:id.json page is supposed to have a next button.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @DanL12186.

We have updated the materials, added in a preventDefault and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
