### ISSUE TITLE
Learn open cannot find this lab

### ISSUE THREAD

**Issue by anginblu** [learn-co-curriculum/using-to-json-ruby#11]
I had to manually copy to my repository and update.

**Comment by maxwellbenton** [comment]
Thank you for providing feedback, @anginblu.

I was unable to replicate the issue that occurred, but we have updated the materials and confirmed this code along is working correctly.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
