### ISSUE TITLE
Tests -- Failing

### ISSUE THREAD

**Issue by maxgrok** [learn-co-curriculum/using-to-json-ruby#12]
Hello, 

I'm failing tests, but I did the README.md as described. If you could edit the README.md to include extra tasks, then that would be great. 

All the Best,
Max

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @maxgrok.

We have updated this lesson to correctly reflect the content being taught and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
