### ISSUE TITLE
re: unmentioned tests

### ISSUE THREAD

**Issue by DGMarkel** [learn-co-curriculum/using-to-json-ruby#14]
As others have mentioned, would be nice if you mentioned that there are additional tests beyond the readme's codealong section.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @DGMarkel.

We have updated this lessons tests to correctly reflect the content being taught and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
