### ISSUE TITLE
missing author in post_spec.rb

### ISSUE THREAD

**Issue by catquarks** [learn-co-curriculum/using-to-json-ruby#4]
tests won't pass for correctly formatted view page unless @post is associated with an author.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @catquarks.

We have updated the tests to reflect what is being taught in this lesson and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
