### ISSUE TITLE
Tests- Form

### ISSUE THREAD

**Issue by depaolif** [learn-co-curriculum/using-to-json-ruby#8]
The lab starts off with an Author field attached to each Post, but the tests never make an author object to associate with the post object that they test, resulting in errors. There are also tests for forms, which have nothing to do with and were never talked about in the ReadMe. Also, this is listed as a ReadMe, not a lab, so why are there all these tests?

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @depaolif.

We have updated the tests in this lesson to reflect what is taught and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
